# ----------------------------------------------------------------
# AdvancedCoreHub Main Configuration
# ----------------------------------------------------------------

# Default language for the plugin. Corresponds to a file name in the 'languages' folder (e.g., 'en').
language: en

# Spawn location settings. Use /setspawn to set this automatically.
spawn:
  world: world
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

# Actions to be executed when a player joins the server.
# See the action format documentation for all available types.
actions_on_join:
  - "[TITLE]<green>Welcome to the Server!;<gray>Enjoy your stay, %player_name%!;10;70;20"
  - "[SOUND]ENTITY_PLAYER_LEVELUP"

# List of worlds where hub-specific rules should apply (e.g., event cancellation).
disabled_worlds:
  - hub
  - lobby

# Settings for events to cancel in the disabled_worlds list.
# Players with the 'advancedcorehub.bypass.worldguard' permission are immune.
world_settings:
  cancel_block_break: true
  cancel_block_place: true
  cancel_player_damage: true
  cancel_hunger_loss: true
  cancel_weather_change: true

# --- Inventory Management ---
# Settings for how inventories are handled in hub worlds.
inventory_management:
  # Worlds where inventory will be cleared and hub items will be given.
  hub-worlds:
    - "hub"
    - "lobby"
  # Clear inventory when a player enters a hub world.
  clear-on-enter: true
  # More features like save/restore can be added here later.

# Settings for movement items.
movement_items:
  trident:
    return_trident: true
    cooldown: 5 # in seconds
  grappling_hook:
    power: 1.8
    cooldown: 3
  aote:
    distance: 8 # in blocks
    cooldown: 2
  enderbow:
    cooldown: 3

# ----------------------------------------------------------------
# Automatic Announcements
# ----------------------------------------------------------------
announcements:
  enabled: true
  interval_seconds: 90
  # If true, announcements will be chosen randomly. If false, they will be shown in order.
  randomized: false
  # A list of announcements to display. Each announcement is an object with its own properties.
  messages:
    # Example 1: A simple chat message shown to all players.
    - type: CHAT
      message: "<yellow>Don't forget to visit our website at <underline>www.example.com</underline></yellow>"

    # Example 2: An action bar message shown only to players in the 'hub' and 'lobby' worlds.
    - type: ACTION_BAR
      message: "<aqua>You are in the main lobby!"
      worlds:
        - "hub"
        - "lobby"

    # Example 3: A title message. The message is split by ';' into title and subtitle.
    - type: TITLE
      message: "<green>TIP<gray>;<white>You can use <gold>/vote</gold> to support the server!"
      # Optional timing parameters for the title.
      fade-in: 10
      stay: 80
      fade-out: 10

    # Example 4: A boss bar message.
    - type: BOSS_BAR
      message: "<gradient:blue:purple>Join our Discord for updates and events!</gradient>"
      color: PURPLE
      style: SEGMENTED_10
      duration: 10 # in seconds

# Boss bar settings for on-join message.
bossbar:
  show_on_join: true
  title: "<gradient:#5e4fa2:#f79459>Welcome, %player_name%!</gradient>"
  color: WHITE # Can be BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  style: SOLID # Can be SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  duration: 10 # in seconds, use -1 to make it stay forever
