# ----------------------------------------------------------------
# AdvancedCoreHub Main Configuration
# ----------------------------------------------------------------

# Default language for the plugin. Corresponds to a file name in the 'languages' folder (e.g., 'en').
language: en

# Spawn location settings. Use /setspawn to set this automatically.
spawn:
  world: world
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

# Teleport player to spawn on join.
spawn-on-join:
  enabled: true

# General message settings for the plugin.
messages:
  # This prefix will be added to the beginning of most plugin messages.
  # You can leave it empty "" if you don't want a prefix.
  prefix: "<dark_aqua>[AdvancedCoreHub] </dark_aqua>"

# Actions to be executed when a player joins the server.
# See the action format documentation for all available types.
actions_on_join:
  - type: TITLE
    data:
      title: "<green>Welcome to the Server!</green>"
      subtitle: "<gray>Enjoy your stay, %player_name%!</gray>"
      fade-in: 10
      stay: 70
      fade-out: 20
  - type: SOUND
    data: "ENTITY_PLAYER_LEVELUP;1.0;1.2"

# This is the central list of worlds that are considered 'hub' worlds.
# In these worlds, special rules (like event cancellation) and inventory management will apply.
# Use the /setspawn command in a world to automatically add it to this list.
hub-worlds:
  - "hub"
  - "lobby"

# Settings for events to cancel in the hub-worlds list.
# Players with the 'advancedcorehub.bypass.worldguard' permission are immune.
world_settings:
  cancel_block_break: true
  cancel_block_place: true
  cancel_player_damage: true
  cancel_hunger_loss: true
  cancel_weather_change: true

# --- Chat Protection ---
# Settings for anti-swear and command blocking.
chat_protection:
  anti_swear:
    enabled: true
    # A list of words to block in chat. Not case-sensitive.
    blocked_words:
      - "badword1"
      - "example"
      - "swear"
  command_blocker:
    enabled: true
    # A list of commands to block. Do not include the leading '/'.
    # This will block '/plugins' and '/pl', and also variants like '/bukkit:plugins'.
    blocked_commands:
      - "plugins"
      - "pl"
      - "ver"
      - "version"
      - "?"
      - "about"
      - "icanhasbukkit"

# --- Anti World Downloader ---
# Prevents players from using World Downloader mods.
anti_world_downloader:
  enabled: true

# --- Inventory Management ---
# Settings for how inventories are handled in hub worlds.
inventory_management:
  # When enabled, inventory will be cleared and hub items will be given upon entering a hub world.
  # This feature uses the 'hub-worlds' list defined above.
  enable: true
  # If true, player inventories will be saved when entering a hub world and restored when leaving.
  # This prevents item loss when moving between game worlds and hub worlds.
  save-and-restore: true
  clear-on-enter: true

# Settings for the server selector menu
server-selector:
  # A list of BungeeCord/Velocity server names to get player counts for.
  # This must match the server names in your proxy's configuration.
  servers:
    - "survival"
    - "creative"
    - "skyblock"

# --- Player Visibility ---
# Settings for the player visibility feature in hub worlds.
player-visibility:
  # If enabled, players will receive an item to toggle the visibility of other players.
  enabled: true
  # The default visibility state for players when they join.
  # true = players are visible, false = players are hidden.
  default_state: true
  # The slot in the hotbar where the visibility item will be placed. (0-8)
  item_slot: 8
  # Settings for the item when players are visible.
  item_visible:
    material: "LIME_DYE"
    name: "<green>Players: Visible</green>"
    lore:
      - "<gray>Click to hide all players."
  # Settings for the item when players are hidden.
  item_hidden:
    material: "GRAY_DYE"
    name: "<red>Players: Hidden</red>"
    lore:
      - "<gray>Click to show all players."

# Settings for movement items.
movement_items:
  trident:
    return_trident: true
    cooldown: 5 # in seconds
  grappling_hook:
    power: 1.8
    cooldown: 3
  aote:
    distance: 8 # in blocks
    cooldown: 2
  enderbow:
    cooldown: 3
  custom_elytra:
    cooldown: 10
    speed_boost: 1.8

# Settings for the Double Jump feature.
double_jump:
  enabled: true
  # Cooldown in seconds between each double jump.
  cooldown: 2
  # The vertical power of the jump.
  power: 1.2
  # Sound played on double jump.
  sound:
    name: "ENTITY_FIREWORK_ROCKET_LAUNCH"
    volume: 1.0
    pitch: 1.0

# ----------------------------------------------------------------
# Automatic Announcements
# ----------------------------------------------------------------
announcements:
  enabled: true
  interval_seconds: 90
  # If true, announcements will be chosen randomly. If false, they will be shown in order.
  randomized: false
  # A list of announcements to display. Each announcement is an object with its own properties.
  messages:
    # Example 1: A simple chat message shown to all players.
    - type: CHAT
      message: "<yellow>Don't forget to visit our website at <underline>www.example.com</underline></yellow>"

    # Example 2: An action bar message shown only to players in the 'hub' and 'lobby' worlds.
    # Note: This 'worlds' list is specific to this announcement and is not affected by the main 'hub-worlds' list.
    - type: ACTION_BAR
      message: "<aqua>You are in the main lobby!"
      worlds:
        - "hub"
        - "lobby"

    # Example 3: A title message with structured data.
    - type: TITLE
      title: "<green>TIP</green>"
      subtitle: "<white>You can use <gold>/vote</gold> to support the server!</white>"
      fade-in: 10
      stay: 80
      fade-out: 10
      worlds: ["hub"] # This title will only show in the 'hub' world

    # Example 4: A boss bar message.
    - type: BOSS_BAR
      message: "<gradient:blue:purple>Join our Discord for updates and events!</gradient>"
      color: PURPLE
      style: SEGMENTED_10
      duration: 10 # in seconds

# Boss bar settings for on-join message.
bossbar:
  show_on_join: true
  title: "<gradient:#5e4fa2:#f79459>Welcome, %player_name%!</gradient>"
  color: WHITE # Valid colors: BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  style: SOLID # Valid styles: SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  duration: 10 # in seconds, use -1 to make it stay forever

# ----------------------------------------------------------------
# Custom Actions
# ----------------------------------------------------------------
# Define your own custom actions here. Each key is the action name you will use in other configs.
# For example, you can then use "[example_action]" or "[greet:Jules]" in your items or menus.
custom-actions:
  example_action:
    actions:
      - "[LANG] custom-actions.example_action.message"
      - "[SOUND] ENTITY_EXPERIENCE_ORB_PICKUP:1.0:1.5"
      - "[CONSOLE] say The player %player_name% just triggered a custom action."
  greet:
    # Usage: [greet:PlayerName] -> will be replaced with %arg1%
    actions:
      - "[LANG] custom-actions.greet.message"
      - "[SOUND] ENTITY_VILLAGER_AMBIENT:1.0:1.0"
