# ----------------------------------------------------------------
# AdvancedCoreHub Main Configuration
# ----------------------------------------------------------------

# Default language for the plugin. Corresponds to a file name in the 'languages' folder (e.g., 'en').
language: en

# Spawn location settings. Use /setspawn to set this automatically.
spawn:
  world: world
  x: 0.5
  y: 100.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

# Actions to be executed when a player joins the server.
# See the action format documentation for all available types.
actions_on_join:
  - "[TITLE]<green>Welcome to the Server!;<gray>Enjoy your stay, %player_name%!;10;70;20"
  - "[SOUND]ENTITY_PLAYER_LEVELUP"

# List of worlds where hub-specific rules should apply (e.g., event cancellation).
disabled_worlds:
  - hub
  - lobby

# Settings for events to cancel in the disabled_worlds list.
# Players with the 'advancedcorehub.bypass.worldguard' permission are immune.
world_settings:
  cancel_block_break: true
  cancel_block_place: true
  cancel_player_damage: true
  cancel_hunger_loss: true
  cancel_weather_change: true

# --- Inventory Management ---
# Settings for how inventories are handled in hub worlds.
inventory_management:
  # Worlds where inventory will be cleared and hub items will be given.
  hub-worlds:
    - "hub"
    - "lobby"
  # Clear inventory when a player enters a hub world.
  clear-on-enter: true
  # More features like save/restore can be added here later.

# Settings for movement items.
movement_items:
  trident:
    return_trident: true
    cooldown: 5 # in seconds
  grappling_hook:
    power: 1.8
    cooldown: 3
  aote:
    distance: 8 # in blocks
    cooldown: 2
  enderbow:
    cooldown: 3

# Automatic announcements settings.
announcements:
  enabled: true
  interval_seconds: 90
  display_mode: CHAT # Can be CHAT or BOSS_BAR
  boss_bar_color: YELLOW # Default color for announcements
  boss_bar_style: SOLID # Default style for announcements
  boss_bar_duration: 10 # in seconds
  messages:
    - "<yellow>Don't forget to visit our website at <underline>www.example.com</underline></yellow>"
    - "<yellow>You can vote for our server using <green>/vote</green>!</yellow>"
    - "<yellow>Join our Discord server for updates and events!</yellow>"

# Boss bar settings.
bossbar:
  show_on_join: true
  title: "<gradient:#5e4fa2:#f79459>Welcome, %player_name%!</gradient>"
  color: WHITE # Can be BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  style: SOLID # Can be SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, SEGMENTED_20
  duration: 10 # in seconds, use -1 to make it stay forever
